wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1631170463
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.11
      5: 0.12.1
      8:
      - 3
      - 5
model_name:
  desc: null
  value: FFA_Net
