wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1636438423
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 16
      - 17
      4: 3.9.6
      5: 0.12.6
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 4
dataset:
  desc: null
  value: NTIRE_Dataset
epochs:
  desc: null
  value: 20
image_size:
  desc: null
  value:
  - 256
  - 256
init_lr:
  desc: null
  value: 0.0001
model_name:
  desc: null
  value: DPT_finetuning
